### ISSUE TITLE
[DATAMODEL] Define enumeration for Institutie

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#1]
Tip de date enumerare care sa cuprinda valorile posibile pentru Institutia in cadrul careia persoana publica isi desfasoara activitatea.
Valori posibile:

* CAMERA DEPUTATILOR
* SENAT
* GUVERNUL ROMANIEI
* PARLAMENTUL ROMANIEI
* SECRETARIATUL GENERAL AL GUVERNULUI
* MINISTERUL DEZVOLTARII REGIONALE SI ADMINISTRATIEI PUBLICE
* MINISTERUL MEDIULUI
* MINISTERUL AFACERILOR INTERNE
* MINISTERUL AFACERILOR EXTERNE
* MINISTERUL APĂRĂRII NAŢIONALE
* MINISTERUL FINANŢELOR PUBLICE
* MINISTERUL JUSTIŢIEI
* MINISTERUL AGRICULTURII ȘI DEZVOLTĂRII RURALE
* MINISTERUL EDUCAŢIEI NAŢIONALE
* MINISTERUL MUNCII ȘI JUSTIȚIEI SOCIALE
* MINISTERUL ECONOMIEI
* MINISTERUL ENERGIEI
* MINISTERUL TRANSPORTURILOR
* MINISTERUL FONDURILOR EUROPENE
* MINISTERUL PENTRU MEDIUL DE AFACERI, COMERȚ ȘI ANTREPRENORIAT
* MINISTERUL SĂNĂTĂŢII
* MINISTERUL CULTURII ȘI IDENTITĂȚII NAȚIONALE
* MINISTERUL APELOR ȘI PĂDURILOR
* MINISTERUL CERCETĂRII ȘI INOVĂRII
* MINISTERUL COMUNICAȚIILOR ȘI SOCIETAȚII INFORMAŢIONALE
* MINISTERUL TINERETULUI ȘI SPORTULUI
* MINISTERUL TURISMULUI
* MINISTERUL PENTRU ROMÂNII DE PRETUTINDENI
* MINISTERUL PENTRU RELAŢIA CU PARLAMENTUL
* ALTA VALOARE

**Comment by radu-diaconescu13** [comment]
It is done :)

**Comment by RaduCStefanescu** [comment]
Done
