### ISSUE TITLE
Create XOR functionality

### ISSUE THREAD

**Issue by catileptic** [code4romania/catpol-declaratii#120]
We need a way to allow the user which of two different options is applicable. This kind of behaviour needs to be implemented across tasks, models and views. 

Two examples:
1. The case of city versus commune. The address can only contain one of the two.
2. The case of the lender being either a person or an institution (in the case of `OwnedDebts`).

The simple way to do it is create a form which allows the user to enter either value.     

The more complicated, but correct way to do it is to have two separate input fields. When one is selected, the other one is greyed out. If the string is deleted from the first, the second becomes enabled.

**Comment by RaduCStefanescu** [comment]
Hi @catileptic 
Have a look at this branch, I started implementing a validation for forms: https://github.com/code4romania/catpol-declaratii/commits/devel_issue%2377

It is not yet complete, but I think we can achieve the functionality you mention above.

**Comment by Iftimie** [comment]
Hi!
I am looking on it now

**Comment by vtemian** [comment]
After some discussions with @catileptic, a more obvious and simple solution would be to unify the fields
`city_commune` and `person_institution`.

**Comment by catileptic** [comment]
Fixed by #207
