### ISSUE TITLE
Explain edge cases in introductory text

### ISSUE THREAD

**Issue by catileptic** [code4romania/catpol-declaratii#128]
Edge cases:   
1. Some people entered more than one value per row. ([see example, page 3](http://www.cdep.ro/declaratii/deputati/2016/avere/033c.pdf)). The volunteer should be instructed to count this as three rows, now one.

**Comment by tudoramariei** [comment]
Would the same apply for II-2 where 3 years were put for one item?
Also, I'm guessing by the example from page 3 you're talking about the USD+EURO+GBP account.

**Comment by tudoramariei** [comment]
I'll be taking this. Should already have a solution for it.
