### ISSUE TITLE
[UI] Internationalization

### ISSUE THREAD

**Issue by catileptic** [code4romania/catpol-declaratii#14]
All strings used in the UI should be:
* referenced;
* replaceable (for localization purposes).

For details on how internationalization & localization work in Django, see:
* [internationalization and localization](https://docs.djangoproject.com/en/2.1/topics/i18n/)
* [translation](https://docs.djangoproject.com/en/2.1/topics/i18n/translation/)

**Comment by tsundokul** [comment]
Working on it

**Comment by tsundokul** [comment]
For those of you using virtualenv(s) and get the message `ModuleNotFoundError: No module named 'project_template'` when running `django-admin`, the only workaround I could find is to copy the script in the project root, as in `catpol-declaratii$ cp $(which djang-admin) .`, and use it from there

**Comment by catileptic** [comment]
Closed by [4f6b348](https://github.com/code4romania/catpol-declaratii/commit/4f6b3486a20694d3b43c1e5c102c88bffad2e9bd) (@tsundokul ).
