### ISSUE TITLE
Missing information for "titular" (owner)

### ISSUE THREAD

**Issue by catileptic** [code4romania/catpol-declaratii#143]
The following classes in `tasks.py` are missing the creation of an "owner" instance in `save_verfied_data`:
* `TaskOwnedGoodsOrServicesRowEntry`
* `TaskOwnedIncomeFromInvestmentsRowEntry`
* `TaskOwnedIncomeFromPensionsRowEntry` (`owner_person` instance not linked as foreign key in `owned_income_from_pensions`)
* `TaskOwnedIncomeFromAgriculturalActivitiesRowEntry`
* `TaskOwnedIncomeFromOtherSourcesRowEntry` (`owner` instance not created separately, instead it is merged into the `owned_income_other_sources` instance, which should fail on execution)

**Comment by catileptic** [comment]
`TaskOwnedGoodsOrServicesRowEntry` fixed. Remaining: 

* `TaskOwnedIncomeFromInvestmentsRowEntry`
* `TaskOwnedIncomeFromPensionsRowEntry` (`owner_person` instance not linked as foreign key in `owned_income_from_pensions`)
* `TaskOwnedIncomeFromAgriculturalActivitiesRowEntry`
* `TaskOwnedIncomeFromOtherSourcesRowEntry` (`owner instance` not created separately, instead it is merged into the `owned_income_other_sources` instance, which should fail on execution)

**Comment by cnstlungu** [comment]
@catileptic 

I would like to help here but would require a little help. OK to ask you a few questions?

**Comment by tudoramariei** [comment]
I'd like to take the rest of this task if it's available
