### ISSUE TITLE
Model-task mismatches: Cannot resolve keyword 'person' into field.

### ISSUE THREAD

**Issue by cnstlungu** [code4romania/catpol-declaratii#156]
The following tasks are producing a "Cannot resolve keyword 'person' into field." error when submitting the form.

- TaskOwnedGoodsOrServicesRowEntry
- TaskOwnedIncomeFromDeferredUseOfGoodsRowEntry
- TaskOwnedIncomeFromGamblingRowEntry
- TaskOwnedIncomeFromSalariesRowEntry

The task at hand is to fix the discrepancies between the form/task and the model.

**Comment by tudoramariei** [comment]
Seems like the only tasks remaining right now are:
- [ ] TaskOwnedIncomeFromDeferredUseOfGoodsRowEntry
- [ ] TaskOwnedIncomeFromGamblingRowEntry
- [ ] TaskOwnedIncomeFromSalariesRowEntry

OwnedIncomeFromIndependentActivitiesTableEntry is in the works by @catileptic
