### ISSUE TITLE
Missing child classes - TaskTranscribeOwnedInvestmentsTable & TaskOwnedIncomeFromIndependentActivitiesTable

### ISSUE THREAD

**Issue by cnstlungu** [code4romania/catpol-declaratii#157]
_TaskTranscribeOwnedInvestmentsTable_ and _TaskOwnedIncomeFromIndependentActivitiesTable_ have no child classes defined. 

As part of this story, please also investigate whether _TaskTranscribeOwnedInvestmentsTable_   (and its corresponding model) is deprecated, since we already have the similarly name _TaskOwnedIncomeFromInvestmentsTable_.

**Comment by catileptic** [comment]
Taking this

**Comment by catileptic** [comment]
Fixed by [cdab3a0d1d1a80f8fb64ff247d2cd85a755aa488](https://github.com/code4romania/catpol-declaratii/commit/cdab3a0d1d1a80f8fb64ff247d2cd85a755aa488) and [eac5a8d6b49c6b6ba5147a40702528add2908836](https://github.com/code4romania/catpol-declaratii/commit/eac5a8d6b49c6b6ba5147a40702528add2908836)
