### ISSUE TITLE
[Infrastructure] Docker container for running PyBossa

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#158]
PYBOSSA is the ultimate crowdsourcing framework to analyze or enrich data
that can't be processed by machines alone.

PyBossa is a dependency for asset declarations project of catalog politic and we need an instance to be deployed and used for development and production environments.

The best solution is to have a Docker container running the PyBossa instance, and this instance will be shared by developers working on the solution and also by the production environment when we have it up and running.

The container needs to be automatically deployed to AWS infrastructure using Travis CI.

**Comment by catileptic** [comment]
We are currently waiting for [a critical PR](https://github.com/Scifabric/pybossa-client/pull/34) to be merged into the PyBossa solution.

**Comment by catileptic** [comment]
PyBossa will no longer be used for this project. It has been removed from Moonsheep.
