### ISSUE TITLE
[Infrastructure] Integrate catpol-declaratii solution with PyBossa instance

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#160]
Issue linked to these 2 issues:
#158 
#159 

The catpol-solutii instance running in a Docker container needs to be integrated with the PyBossa instance.

**Comment by catileptic** [comment]
We are currently waiting for [a critical PR](https://github.com/Scifabric/pybossa-client/pull/34) to be merged into the PyBossa solution.

**Comment by catileptic** [comment]
PyBossa will no longer be used for this project. It has been removed form Moonsheep as a dependency.
