### ISSUE TITLE
The forms' year choices values are only computed at server start

### ISSUE THREAD

**Issue by danniel** [code4romania/catpol-declaratii#162]
The values for YEAR_CHOICES and YEAR_DICT_CHOICES are computed when Python loads the `forms.py` file. Each `widget=forms.SelectDateWidget(years=YEAR_CHOICES)` will set the same choices (1980, ..., 2019) even if called after a couple of years.

In order to fix this, YEAR_CHOICES and YEAR_DICT_CHOICES must be callables which would dynamically build the choice tuples when called.

**Comment by catileptic** [comment]
Good point!

**Comment by tudoramariei** [comment]
Taking this one
