### ISSUE TITLE
share_ratio Decimal size

### ISSUE THREAD

**Issue by danniel** [code4romania/catpol-declaratii#175]
in `models.py` the `share_ratio` has a different Decimal size for different models even if it seems to be used for the same purpose. 

For example:

***`class OwnedLandTableEntry(CommonInfo):`***
`share_ratio = models.DecimalField("Cota-parte", max_digits=5, decimal_places=2)`
(allows values as XXX.XX)

***`class OwnedBuildingsTableEntry(CommonInfo):`***
`share_ratio = models.DecimalField("Cota de participare", max_digits=3, decimal_places=2, null=True, blank=True)`
(allows values as X.XX)

***`class OwnedInvestmentsOver5KTableEntry(models.Model):`***
`share_ratio = models.DecimalField("Cota de participare", max_digits=3, decimal_places=2, null=True, blank=True)`
(allows values as X.XX)

It's really not clear if one should think of the share_ratio as ***(a)*** something from 0 to 1 (for example the field value of 0.335 meaning a 33.5% share ratio), or as ***(b)*** percentage points where a field value of 33.5 means 33.5% share ratio.

If we go with option ***(a)***, then the `OwnedLandTableEntry` `share_ratio` definition should have `max_digits=3` and `decimal_places=2`.

**Comment by danniel** [comment]
On the other hand, in the Form field the app expects integers between 0 and 100 for `percent_of_ownership` and, on Task save, the data does not seem to be transformed to the database expected format for `share_ratio`. 

That's why setting a `percent_of_ownership` to 0 or 1 or 9 works, while 10, 11, 99 raises `<class 'decimal.InvalidOperation'>` when trying to save data about Owned Buildings.

**Comment by alexandra-stefanescu** [comment]
This is great digging and a great summary of the issue!

On the other hand, it occurs to me, reading this, that there might be people who have filled the asset declaration form in with a percent of `89.78`. I hope this isn't the case, but what if it is?

Regardless, I think we should address this issue as part of the refactoring needed to merge [this PR](https://github.com/code4romania/catpol-declaratii/pull/169). 

What do you think?

**Comment by RaduCStefanescu** [comment]
Great point @danniel 
The way I see it the share_ratio should be in the form of 33.5 -> meaning 33.5%.
One way to implement this would be to implement a factory of model fields, that get as input just the name of the field. For example in our case, have a factory method that returns share_ratio type of fields, with let's say 'max_digits=3' and 'decimal_places=1'.

**Comment by catileptic** [comment]
This is great digging and a great summary of the issue!

On the other hand, it occurs to me, reading this, that there might be people who have filled the asset declaration form in with a percent of `89.78`. I hope this isn't the case, but what if it is?

Regardless, I think we should address this issue as part of the refactoring needed to merge [this PR](https://github.com/code4romania/catpol-declaratii/pull/169).

What do you think?

**Comment by danniel** [comment]
I will make all three fields to be max_digits=5, decimal_places=2

This way we can allow values as 100.00 for (100%)
A custom validator will prevent the input of values over 100.00
