### ISSUE TITLE
[DATAMODEL] Define enumeration for Tip declaratie

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#2]
Declaratiile depuse de persoanele publice pot fi de doua tipuri, declaratii de avere si declaratii de interes. Acest enum trebuie sa contina valorile posibile pentru tipurile de declaratii pe care vonluntarii le digitalizeaza:
* INTERESE
* AVERE

**Comment by radu-diaconescu13** [comment]
It is done already :)

**Comment by RaduCStefanescu** [comment]
Done
