### ISSUE TITLE
[DATAMODEL] Define enumeration for Natura Bunuri Mobile

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#3]
Introducere enumeratie pentru parsarea datelor despre natura bunurilor mobile detinute. Aceasta poate avea urmatoarele valori:

* AUTOVEHICULE/AUTOTURISME
* TRACTOARE
* MASINI AGRICOLE
* SALUPE
* IAHTURI
* ALTELE

**Comment by radu-diaconescu13** [comment]
I am doing this :)

**Comment by catileptic** [comment]
This issue is closed by @radu-diaconescu13, by [01aa2ae](https://github.com/code4romania/catpol-declaratii/commit/01aa2aee6b96b1477d2a2ef9bbc2d3c13b1fc517).
