### ISSUE TITLE
[MICROTASK] Introducere numar randuri tabel Bunuri Imobile - Terenuri

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#5]
**Scop**: un task în care utilizatorul este rugat să introducă numărul de rânduri din tabelul intitulat *Bunuri Imobile - Terenuri*. 

Acest task va popula modelul de date `OwnedLandTable` din `models.py`.   

În UI, acest task va cere utilizatorului să introducă doar numărul de rânduri completate (care conțin informație) din tabelul *Bunuri Imobile - Terenuri*. 

Un task nou se adaugă în `tasks.py`.    
Orice task nou moștenește `AbstractTask`.    
Pentru referință, urmăriți modelul lui `TaskGetInitialInformation`.   
Orice task nou are atributele: 
* `task_form` - definește structura `form`-urilor de completat din UI, se populează în `forms.py`
* `template_name` - un template HTML care definește structura paginii din UI.   

Orice task nou trebuie să definească metodele:
* `create_mocked_task` (va genera un task de test - pentru debugging)
* `get_presenter` (poate fi luată cu copy/paste metoda din `TaskGetInitialInformation`)
* `save_verified_data` (primește ca parametru `verified_data`, un dicționar care are ca și chei numele variabilelor din `task_form`-ul corespunzător - acest dicționar va fi folosit pentru a popula `model`-ul asociat)
* `after_save` (metodă folosită pentru a link-ui task-uri - poate fi lăsată fără implementare)

**Comment by sAstrid** [comment]
Bucuresti

**Comment by RaduCStefanescu** [comment]
Issues addressed in https://github.com/code4romania/catpol-declaratii/pull/61
