### ISSUE TITLE
[DATAMODEL] Define enumeration for Valuta

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#50]
Definit enumeratie pentru valuta folosita in aplicatie, trebuie sa contina urmatoarele valori:
* EUR
* RON
* USD
* GBP
* CAD
* CHF
* ALTELE

**Comment by radu-diaconescu13** [comment]
It is done already

**Comment by RaduCStefanescu** [comment]
Done
