### ISSUE TITLE
[DATAMODEL] Define enumeration for Functie

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#6]
Ca parte a parsarii declaratiilor de avere, avem nevoie de o enumerare care sa contina functiile posibile pe care o persoana publica le poate detine. Acestea sunt:

* SECRETAR GENERAL
* DEPUTAT
* SENATOR
* PARLAMENTAR
* PRIM-MINISTRU
* VICEPRIM-MINISTRU
* MINISTRU
* PRESEDINTE
* PRESEDINTE CAMERA DEPUTATILOR
* PRESEDINTE SENAT
* CONSILIER
* SECRETAR DE STAT
* ALTA VALOARE

**Comment by radu-diaconescu13** [comment]
It is done already :)

**Comment by RaduCStefanescu** [comment]
Done
