### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel I. Bunuri imobile - 1. Terenuri

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#63]
Microtask pentru introducerea informatiilor din tabelul I. Bunuri imobile - 1. Terenuri. Acest microtask trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in https://github.com/code4romania/catpol-declaratii/issues/5
Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face highligh pe tabelul I. Bunuri Imobile - 1. Terenuri prin mesaj direct catre vountar, implementat in Form
Form:

Afiseaza mesaj catre voluntar:
"Va rugam introduceti informatiile de pe randul {nr_rand} completat din tabelul de Bunuri Imobile - Terenuri"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel

* Dropdown pt selectie Judet - ENUM pentru Judet
* Dropdown pt selectie Localitate - ENUM de tip Localitate 
* TextBox pt selectie Comuna
* Dropdown pt selectie Categorie Terenuri - ENUM 
* Dropdown cu ani pt selectie An dobandire - ENUM de tip An
* Dropdown pt selectie Mod dobandire - ENUM 
* Textbox pt introducere Suprafata
* Textbox pt introducere Cota parte - trebuie limitata la 100 deoarece reprezinta procente
* Textbox pt introducere Proprietar (Persoana)

Cross-Verification

Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified Data:
Se vor salva urmatoarele db objects care tb definite in models.py

Terenuri
Judet (ENUM)
Localitate (ENUM)
Comuna (STRING)
Categorie (ENUM)
An dobandire (YEAR)
Mod dobandire (ENUM)
Suprafata (NUM)
Cota Parte (NUM)
Coproprietar (PERSOANA)

Persoana
Nume (STRING)
Prenume (STRING)

**Comment by catileptic** [comment]
Taken by @radu-diaconescu13

**Comment by radu-diaconescu13** [comment]
@RaduCStefanescu this is done already

**Comment by RaduCStefanescu** [comment]
This is already done, can be closed.
