### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel I. Bunuri imobile - 2. Cladiri

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#64]
Microtask pentru introducerea informatiilor din tabelul I. Bunuri imobile - 2. Cladiri. Acest microtask trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in https://github.com/code4romania/catpol-declaratii/issues/4
Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face highlight pe tabelul I. Bunuri Imobile - 2. Cladiri prin mesaj direct catre voluntar, implementat in Form

Form:

Afiseaza mesaj catre voluntar: 
"Va rugam introduceti informtiile de pe randul {nr_rand} completat din tabelul de Bunuri Imobile - Terenuri"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel
* Dropdown pt selectie Judet - ENUM de tip Judet
* Dropdown pt selectie Localitate - ENUM de tip Localitate 
* TextBox pt selectie Comuna
* Dropdown pt selectie Categorie - ENUM 
* Dropdown cu ani pt selectie An dobandire
* Dropdown pt selectie Mod dobandire - ENUM 
* Textbox pt introducere Suprafata
* Textbox pt introducere Cota parte - trebuie limitata la 100 deoarece reprezinta procente
* Textbox pt introducere Proprietar (Persoana)

Cross-Verification

Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified Data:
Se vor salva urmatoarele db objects care tb definite in models.py

Cladiri
Judet (ENUM)
Localitate (ENUM)
Comuna (STRING)
Categorie (ENUM)
An dobandire (YEAR)
Mod dobandire (ENUM)
Suprafata (NUM)
Cota Parte (NUM)
Coproprietar (PERSOANA)

Persoana
Nume (STRING)
Prenume (STRING)

**Comment by radu-diaconescu13** [comment]
taking this @radu-diaconescu13
