### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel II. Bunuri mobile - 1. Autovehicule/Autoturisme

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#66]
Microtask pentru introducerea informatiilor din tabelul II. Bunuri mobile - 1. Autoturisme/autovhicule. Acest microtask
trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in https://github.com/code4romania/catpol-declaratii/issues/15
Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face highlight pe tabelul II. Bunuri Mobile - 1. Autoturisme/autovehicule prin mesaj direct catre vountar, implementat in Form

Form:

Afiseaza mesaj catre voluntar:
"Va rugam introduceti informtiile de pe randul {nr_rand} completat din tabelul de Bunuri Mobile - Autoturisme/Autovehicule"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel
Dropdown pt selectie Natura bunului - ENUM 
Textbox pentru introducere Marca
TextBox pt introducere NumarBucati - permite inserarea doar de numerale
Dropdown de tip Year pentru selectia anului de fabricatie
Dropdown pt selectie ModDobandire - ENUM 

Cross-Verification
Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified Data
Se va salva acest db object care tb definit in models.py

Bunuri_mobile
Natura (ENUM)
Marca (STRING)
NumarBucati (NUM)
AnFabricatie (YEAR)
ModDobandire (ENUM)

**Comment by RaduCStefanescu** [comment]
Assigning for testing purposes

**Comment by catileptic** [comment]
Taken by @Katte-13

**Comment by RaduCStefanescu** [comment]
Fixed by https://github.com/code4romania/catpol-declaratii/pull/101
Can be closed.
