### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel IV. Active financiare - 1. Conturi si depozite bancare

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#76]
Microtask pentru introducerea informatiilor din tabelul IV. Active financiare - 1. Conturi si depozite bancare. Acest microtask trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in #18 Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face scroll sau highlight pe tabelul IV. Active financiare - 1. Conturi si depozite bancare folosind fie OCR fie prin mesaj direct catre vountar, implementat in Form

Form:

Afiseaza mesaj catre voluntar in cazul in care highlightul nu se face folosind solutie de OCR

"Va rugam introduceti informtiile de pe randul {nr_rand} completat din tabelul IV. Active Financiare - 1. Conturi si depozite bancare"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel
Dropdown pt selectie Institutie Financiara - ENUM 
Dropdown pt selectie Tip cont
Dropdown pt selectie Valuta contului 
Drowpdown de tip year pentru selectia anului deschiderii contului
Textbox pt introducere valoare Sold cont

Cross-Verification

Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified Data:
Persista urmatorul model definit in models.py
Conturi
Institutia_administrativa (ENUM)
Tip_Cont (ENUM)
Valuta (ENUM)
AnulDeschiderii (YEAR)
Sold (NUM)

**Comment by KovaxG** [comment]
Here's my pull request for this:
https://github.com/code4romania/catpol-declaratii/pull/107

**Comment by RaduCStefanescu** [comment]
This is done in https://github.com/code4romania/catpol-declaratii/pull/107
