### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel IV. Active financiare - 2. Plasamente, investitii directe si imprumuturi acordate

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#77]
Microtask pentru introducerea informatiilor din tabelul IV. Active financiare - 2. Plasamente, investitii directe si imprumuturi acordate. Acest microtask trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in #19 Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face scroll sau highlight pe tabelul IV. Active Financiare - 2. Plasamente, investitii directe si imprumuturi acordate folosind fie OCR fie prin mesaj direct catre vountar, implementat in Form

Form:

Afiseaza mesaj catre voluntar in cazul in care highlightul nu se face folosind solutie de OCR

"Va rugam introduceti informtiile de pe randul {nr_rand} completat din tabelul IV. Active Financiare - Plasamente, investitii directe si imprumuturi acordate"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel
Textbox pt inserare Societate comerciala/Emitent
Textbox pt inserare nume SRL
Textbox pt introducere Nume Persoana (Persoana)
Textbox pt introducere Prenume Persoana (Persoana)
Textbox pt inserare Descriere
Dropdown pt selectie Tip plasament - ENUM 
TextBox pt inserare cota participare - trebuie sa accepte doar numerale
Textbox pt inserare valoare plasament
Dropdown pt selectie Valuta - ENUM 

Cross-Verification

Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified Data:
Persista urmatorul model definit in models.py
Plasamente_investitii
SocietateComerciala (STRING)
SRL (STRING)
PersoanaFizica (PERSOANA)
Descriere (STRING)
Tip (ENUM)
CotaParticipare (NUM)
Valoare (NUM)
Valuta (ENUM)

**Comment by catileptic** [comment]
Fixed by [this commit](https://github.com/code4romania/catpol-declaratii/pull/166).
