### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel VI. Cadouri/Servicii - sectiunea 1.3 Copii

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#81]
Microtask pentru introducerea informatiilor din tabelul VI. Cadouri/Servicii - Sectiunea 1.3 Copii. 

Acest microtask trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in #23 

Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face scroll sau highlight pe tabelul VI. Cadouri/Servicii - sectiunea 1.3 Copii folosind fie OCR fie prin mesaj direct catre vountar, implementat in Form

Form:

Afiseaza mesaj catre voluntar in cazul in care highlightul nu se face folosind solutie de OCR

"Va rugam introduceti informtiile de pe randul {nr_rand} completat din tabelul VI. Cadouri/Servicii - sectiunea 1.3 Copii"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel
Dropdown pt selectie Relatie titular - ENUM 
Textbox pt introducere Nume Persoana (Persoana)
Textbox pt introducere Prenume Persoana (Persoana)
Dropdown pt selectie Judet pt adresa - ENUM de tip Judet 
Dropdown pt selectie Localitate pt adresa - ENUM de tip Localitate 
Textbox pt introducere Comuna pt adresa
Textbox pt introducere Serviciu prestat
Textbox pt introducere Venit anual incasat
Dropdown pt selectie Valuta - ENUM 

Cross-Verification

Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified Data

Se va salva acest db object care tb definit in models.py

Cadouri_servicii
Relatie_titular (ENUM)
Persoana (STRING)
Judet (ENUM)
Localitate (ENUM)
Comuna (STRING)
Serviciu_prestat (STRING)
Venit_anual_incasat (NUM)
Valuta (ENUM)

Persoana
Nume (STRING)
Prenume (STRING)

**Comment by radu-diaconescu13** [comment]
@radu-diaconescu13 Taking this

**Comment by tudoramariei** [comment]
Was this done, @radu-diaconescu13 ? Can the issue be closed?

**Comment by catileptic** [comment]
Fixed by `dab9898a3d4fe8287a9c62aeba7ed25f4c29bcee`.
