### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel VII. Venituri ale declarantului, etc - sectiunea 1. Venituri din salarii

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#82]
Microtask pentru introducerea informatiilor din tabelul VII. Venituri ale declarantului, etc - Sectiunea 1 Venituri din salarii. Acest microtask trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in #24 
Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face scroll sau highlight pe tabelul VII. Venituri ale declarantului si ale membrilor sai de familie - sectiunea 1. Venituri din salarii folosind fie OCR fie prin mesaj direct catre vountar, implementat in Form

Form:

Afiseaza mesaj catre voluntar in cazul in care highlightul nu se face folosind solutie de OCR

"Va rugam introduceti informtiile de pe randul {nr_rand} completat din tabelul VII. Venituri ale declarantului si ale membrilor sai de familie - sectiunea 1. Venituri din salarii"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel
Dropdown pt selectie Relatie titular - ENUM 
Textbox pt introducere Nume Persoana (Persoana)
Textbox pt introducere Prenume Persoana (Persoana)
Textbox pt selectie Sursa venit
Dropdown pt selectie Judet pt adresa - ENUM 
Dropdown pt selectie Localitate pt adresa - ENUM 
Textbox pt introducere Comuna pt adresa
Textbox pt introducere Adresa strainatate
Textbox pt introducere Serviciu prestat
Dropdown pt introducere Functie - https://codeforromania.atlassian.net/browse/CP-40Textbox pt introducere Venit anual incasatDropdown pt selectie Valuta - https://codeforromania.atlassian.net/browse/CP-87

Cross-Verification

Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified DataSe va salva acest db object care tb definit in models.py

Venituri
Relatie_titular (ENUM)
Nume (STRING)
Prenume (STRING)
Adresa (STRING)
Sursa (ENUM)
Institutie (STRING)
Serviciu_prestat (STRING)
Suma (NUM)
Valuta (ENUM)

Persoana
Nume (STRING)
Prenume (STRING)

**Comment by tudoramariei** [comment]
Taking this in Iasi 😄

**Comment by RaduCStefanescu** [comment]
In progress @tudoramariei
