### ISSUE TITLE
[MICROTASK] Introducere informatii rand tabel VII. Venituri ale declarantului, etc - sectiunea 5. Venituri din pensii

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/catpol-declaratii#85]
Microtask pentru introducerea informatiilor din tabelul VII. Venituri ale declarantului, etc - Sectiunea 5. Venituri din pensii. Acest microtask trebuie generat pentru fiecare rand din tabelul de mai sus. Acest microtask trebuie generat in metoda de after_save in cadrul taskului definit in #28 

Microtaskul va primi ca si parametru numarul randului din tabelul mai sus mentionat. Implementarea microtaskului va contine:

Presenter:

Afiseaza pdf ul, se face scroll sau highlight pe tabelul VII. Venituri ale declarantului si ale membrilor sai de familie - sectiunea 5. Venituri din pensii folosind fie OCR fie prin mesaj direct catre vountar, implementat in Form

Form:

Afiseaza mesaj catre voluntar in cazul in care highlightul nu se face folosind solutie de OCR

"Va rugam introduceti informtiile de pe randul {nr_rand} completat din tabelul VII. Venituri ale declarantului si ale membrilor sai de familie - sectiunea 5. Venituri din pensii"

Afiseaza urmatoarele elemente care trebuie completate de catre voluntar din informatiile din tabel
Dropdown pt selectie Relatie titular - ENUM 
Textbox pt introducere Nume Persoana (Persoana)
Textbox pt introducere Prenume Persoana (Persoana)
Textbox pt selectie Sursa venit
Dropdown pt selectie Judet pt adresa - ENUM 
Dropdown pt selectie Localitate pt adresa - ENUM 
Textbox pt introducere Comuna pt adresa
Textbox pt introducere Adresa strainatate
Textbox pt introducere Serviciu prestat
Dropdown pt introducere Functie - ENUM
Textbox pt introducere Venit anual incasat
Dropdown pt selectie Valuta - ENUM

Cross-Verification

Pt fiecare din campuri vom avea criteriul de verificare si acceptare ca fiind egalitatea valorilor introduse de voluntari

Save Verified Data

Se va salva acest db object care tb definit in models.py

Venituri
Relatie_titular (ENUM)
Nume (STRING)
Prenume (STRING)
Adresa (STRING)
Sursa (ENUM)
Institutie (STRING)
Serviciu_prestat (STRING)
Suma (NUM)
Valuta (ENUM)

Persoana
Nume (STRING)
Prenume (STRING)

**Comment by paubric** [comment]
Bucuresti
