### ISSUE TITLE
[DATAMODEL] Define enumeration for Judet si Localitate

### ISSUE THREAD

**Issue by radu-diaconescu13** [code4romania/catpol-declaratii#99]
Folosind informatiile din orase.csv sa se defineasca ENUM ptr Judet si Localitate
[orase.zip](https://github.com/code4romania/catpol-declaratii/files/2896719/orase.zip)

**Comment by radu-diaconescu13** [comment]
taken by @radu-diaconescu13

**Comment by RaduCStefanescu** [comment]
Issue addressed in PR https://github.com/code4romania/catpol-declaratii/pull/108
